remote_theme: pmarsceill/just-the-docs


title: "Change through time, section 01: S23"




footer_content: "Change through time, Spring 2023.<br/>All material on this web site is available on <a href=\"https://github.com/neelsmith/latin101\">github</a> under the Creative Commons Attribution Share-Alike license <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0 <img height=\"15\" width=\"80\" src=\"https://mirrors.creativecommons.org/presskit/buttons/80x15/png/by-sa.png\" /></a>."
